sudo: required

services:
  - docker

before_install: 
  - docker build -t frontend/docker-travis-test -f Dockerfile.dev .

script: 
  - docker run frontend/docker-travis-test npm run test -- --coverage

